### ISSUE TITLE
Virtual account transactions not triggering EconomyTransactionEvent

### ISSUE THREAD

**Issue by turtledude01** [Flibio/EconomyLite#36] opened 2017-03-01 02:21 UTC
I have a plugin Ive been working on that listens to the withdraw/deposit transactions and withdraws/deposits money into a virtual account depending on a config option.  
The problem I'm having is this: When a virtual account has its funds modified, this event does not trigger with the cause supplied by the plugin.  It is instead only triggered with the cause from EconomyLite.  
It would be really nice to have the virtual account causes sent to the event aswell.  Thanks!

**Comment by turtledude01** [comment] 2017-03-01 02:26
Also, seems that a transfer to a virtual account triggers a withdraw instead of a transfer.

**Comment by Flibio** [comment] 2017-03-01 14:34
Could you please send your plugin source code so I could debug this issue?

**Comment by turtledude01** [comment] 2017-03-01 16:51
https://github.com/Radical-Delta/ServerEco/tree/dev

**Comment by Flibio** [comment] 2017-03-01 22:34
Thanks, I'll take a look at it.

**Comment by Flibio** [comment] 2017-03-01 22:45
Where do you see this issue occurring?

> Also, seems that a transfer to a virtual account triggers a withdraw instead of a transfer.

**Comment by turtledude01** [comment] 2017-03-02 00:34
When a transfer to a virtual account happens, my plugin sees a withdraw on the account.  Same happens in reverse when transferring from a virtual account to a player

**Comment by Flibio** [comment] 2017-03-02 04:24
EconomyLite should fire 3 events for every transfer - One withdrawal, one deposit, and one transfer - Are you sure the transfer isn't firing? Maybe you are just picking up the withdrawal, that one would fire first.

**Comment by turtledude01** [comment] 2017-03-02 04:53
Correct me if Im wrong, but the only transaction that triggers with the same cause as the plugin it originated from would be a transfer when transfering from a player to a virtual, and all the others would be the same aswell.  Which they are not.  The specific plugin I am combining with my own and economylite to achieve this issue is nations.  When transfering money into a nation (virtual account) my plugin, which only does anything on a withdraw or deposit, ends up taking it as a withdraw/deposit.  I am not listening for any causes from EconomyLite.

**Comment by Flibio** [comment] 2017-03-03 02:35
The cause tracking should be fixed in v2.10.2. Please let me know how it works for you!

**Closed as completed by Flibio** 2017-03-03 02:35 UTC

**Comment by turtledude01** [comment] 2017-03-03 05:16
@Flibio One small issue has arisen, Now it seems as though a withdraw from a player account is causing a withdraw, then a deposit cause to be triggered... Effectively making my plugin believe there was $0 transferred... I'm testing this a bit more for now, but it does seem to be doing some funky things.

**Comment by turtledude01** [comment] 2017-03-03 05:21
[servereco]: Cause for transaction: nations
[servereco]: Cause for transaction: servereco
[servereco]: Transaction of 2500.0 to/from Server Success! 
//(probably the withdraw originally being put into the server account)
[servereco]: Cause for transaction: nations
[servereco]: Cause for transaction: servereco
[servereco]: Transaction of 2500.0 to/from Server Success! 
//(seems to be the withdraw being reverted as a deposit? but no money is returned to the player)
[servereco]: Cause for transaction: nations
[servereco]: Cause for transaction: servereco
[servereco]: Transaction of 0 to/from Server Success!
//(This one im completely confused about)

**Comment by Flibio** [comment] 2017-03-03 14:45
> Now it seems as though a withdraw from a player account is causing a withdraw, then a deposit cause to be triggered

That would make sense, as money is withdrawn from the player's account and then deposited into the other account.

**Comment by turtledude01** [comment] 2017-03-03 14:50
Yeah, My plugin does not listen to transfers for anything other than debug.  And this was a transfer that caused both a withdraw then a deposit

**Comment by Flibio** [comment] 2017-03-03 14:51
> Now it seems as though a withdraw from a player account is causing a withdraw, then a deposit cause to be triggered

This is caused by your plugin, ServerEco. Take a look at [these three lines of code](https://github.com/Radical-Delta/ServerEco/blob/master/src/main/java/org/radicaldelta/turtledude01/servereco/ServerEco.java#L107-L109). On a withdraw, you initiate a deposit, therefore causing the deposit event you are seeing.

**Comment by turtledude01** [comment] 2017-03-03 14:54
Nope, that transaction causes the 'Cause of transaction: Servereco' which is not acted upon (I dont have the plugin configured to do anything if the plugin is ServerEco).  Nations however is getting an extra deposit cause

**Comment by Flibio** [comment] 2017-03-03 14:55
How are you getting this extra deposit cause to appear? By running a transfer, withdraw, or deposit?

**Comment by turtledude01** [comment] 2017-03-03 14:56
A transfer from a player to a virtual

edit; NO, thats not a transfer, its a withdraw, sorry

**Comment by Flibio** [comment] 2017-03-03 15:00
And how many events are thrown and of what type?

**Comment by turtledude01** [comment] 2017-03-03 15:01
Nations is throwing a WIthdraw, then a deposit, then something with $0.  
The strange thins is that the second deposit only takes the money away from the virtual account, and does not return it to the player.

**Comment by Flibio** [comment] 2017-03-03 15:03
What is the "second deposit" if there is only one deposit? Is the something a deposit or a transfer?

> Nations is throwing a WIthdraw, then a deposit, then something with $0.

**Comment by turtledude01** [comment] 2017-03-03 15:04
sorry, meant that as its the second transaction that happens, which should not happen.  
I have to go to school now, Ill work on finding more info about this when I get home.  

Thanks

**Comment by Flibio** [comment] 2017-03-04 14:12
I'm still not quite sure what the actual issue is. Could you please explain it?

The mystery $0 deposit is due to Nations setting the balance to of the nation to 0, there is no transaction type for setting the balance, so I just went with deposit.

**Comment by turtledude01** [comment] 2017-03-05 17:39
Ok, the $0 makes sense now, but this is happening when creating a nation, which is a withdraw.  When this withdraw happens its suddenly and for no reason, returning it with a deposit of the same amount... 
But heres where it gets interesting... The deposit doesnt actually affect the users account... Only the virtual account that my plugin is handling.

**Comment by Flibio** [comment] 2017-03-05 21:26
Can you enable the debug option in EconomyLite, run exactly what reproduces this issue, and send the `fml-server-latest.log` file?
